# Generated by Django 6.0.7 on 2026-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('u', 'Urgent'), ('c', 'Critical')], max_length=15, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done'), ('closed', 'Closed')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
