# Generated by Django 6.0.7 on 2026-08-07 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.csv', '.doc', '.xlsx', '.py', '.txt'])]),
        ),
    ]
