# Generated by Django 6.0.7 on 2026-08-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
