# Generated by Django 6.0.7 on 2026-08-20 11:27

import apps.projects.utils.upload_file_helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/', validators=[apps.projects.utils.upload_file_helpers.validate_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'doc', 'xlsx', 'py', 'txt', 'png', 'jpeg', 'jpg']), apps.projects.utils.upload_file_helpers.validate_file_size]),
        ),
    ]
