# Generated by Django 6.0.7 on 2026-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at_user_deleted_at_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('dsg', 'Designer'), ('prg', 'Programmer'), ('prdo', 'Prod'), ('pro', 'Project Owner'), ('prm', 'Project Manager'), ('qa', 'QA')], default='qa', verbose_name='Positions'),
            preserve_default=False,
        ),
    ]
