# Generated by Django 6.0.7 on 2026-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('dsg', 'Designer'), ('prg', 'Programmer'), ('prdo', 'Product Owner'), ('pro', 'Project Owner'), ('prm', 'Project Manager'), ('qa', 'QA')], max_length=4, verbose_name='Positions'),
        ),
    ]
