"""
Django settings for config projects.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.contrib.admindocs.utils import ROLES
from environ import Env

# Build paths inside the projects like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.projects.apps.ProjectConfig',
    # 'apps.user.apps.UserConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
AUTH_USER_MODEL = 'auth.User' # Switching between auth.User and 'user.User'

ROLE_PERMISSION = {
    'Managers': [
        'auth.group.view',
        'auth.user.add',
        'auth.user.view',
        'auth.permission.add',
        'auth.permission.view',
        'projects.tag.add',
        'projects.tag.change',
        'projects.tag.view',
        'projects.project.add',
        'projects.project.view',
        'projects.project.delete',
        'projects.project.change',
        'projects.task.add',
        'projects.task.change',
        'projects.task.view',
        'projects.projectfile.view',
        'projects.projectfile.add',
        'projects.projectfile.change',
        'projects.projectfile.delete'
        ],
    'Clients': [
        'auth.user.add',
        'auth.user.change',
        'auth.user.view',
        'projects.project.add',
        'projects.project.change',
        'projects.project.view',
        'projects.projectfile.add',
        'projects.projectfile.view',
        'projects.tag.add',
        'projects.tag.change',
        'projects.tag.delete',
        'projects.tag.view',
        'projects.task.add',
        'projects.task.change',
        'projects.task.delete',
        'projects.task.view',
    ],
    'Developers': [
            'auth.user.add',
            'auth.user.change',
            'auth.user.view',
            'auth.user.delete',
            'projects.project.add',
            'projects.project.change',
            'projects.project.view',
            'projects.project.delete',
            'projects.projectfile.add',
            'projects.projectfile.change',
            'projects.projectfile.delete',
            'projects.projectfile.view',
            'projects.tag.add',
            'projects.tag.change',
            'projects.tag.delete',
            'projects.tag.view',
            'projects.task.add',
            'projects.task.change',
            'projects.task.delete',
            'projects.task.view',
        ]
}